#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "path"
    style = "plain"
    background = "transparent"
    foreground = "white"
    template = "{{.Path}}"

    [blocks.segments.properties]
      style = "full"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "cyan"
    background = "transparent"
    template = " {{.HEAD}}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<cyan>{{ if gt .Behind 0 }}-\uf175{{ end }}{{ if gt .Ahead 0 }}-\uf176{{ end }}</>"

    [blocks.segments.properties]
      branch_icon = "\ue0a0-"
      commit_icon = "@"
      fetch_status = true

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "yellow"
    background = "transparent"
    template = " {{ .FormattedMs }}"

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = "transparent"
    template = "{{.UserName}} \uf054"

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = "transparent"
  template = "\uf054 "

[secondary_prompt]
  foreground = "magenta"
  background = "transparent"
  template = "\uf054\uf054 "
